"""add_product_variants_and_options

Revision ID: 913c2e31893f
Revises: eaa47f187470
Create Date: 2026-06-07 13:10:38.940439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '913c2e31893f'
down_revision: Union[str, Sequence[str], None] = 'eaa47f187470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_options', sa.JSON(), nullable=True))

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_options', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('resolved_image_url', sa.String(length=512), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variants', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('variants')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('resolved_image_url')
        batch_op.drop_column('selected_options')

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_column('selected_options')

    # ### end Alembic commands ###
