"""Add razorpay_order_id and webhook_events

Revision ID: 9ba56e49a4cf
Revises: d4e5f6a7b8c9
Create Date: 2026-07-08 19:10:20.257354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ba56e49a4cf'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razorpay_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_events_razorpay_event_id'), ['razorpay_event_id'], unique=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razorpay_order_id', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_orders_razorpay_order_id', ['razorpay_order_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('uq_orders_razorpay_order_id', type_='unique')
        batch_op.drop_column('razorpay_order_id')

    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_events_razorpay_event_id'))
        batch_op.drop_index(batch_op.f('ix_webhook_events_id'))

    op.drop_table('webhook_events')
    # ### end Alembic commands ###
