"""add banners table

Revision ID: eaa47f187470
Revises: b8f1e2a3c4d5
Create Date: 2026-04-19 15:29:17.666442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaa47f187470'
down_revision: Union[str, Sequence[str], None] = 'b8f1e2a3c4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('cta_text', sa.String(length=50), nullable=True),
    sa.Column('cta_link', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('image_public_id', sa.String(length=255), nullable=True),
    sa.Column('badge_text', sa.String(length=100), nullable=True),
    sa.Column('bg_color', sa.String(length=20), nullable=False),
    sa.Column('text_color', sa.String(length=20), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('placement', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_banners_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_banners_id'))

    op.drop_table('banners')
    # ### end Alembic commands ###
